-- Table: public."SourceDecks"

-- DROP TABLE public."SourceDecks";

CREATE TABLE public."SourceDecks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Uuid" text NOT NULL,
    "ApiData" text NOT NULL,
    CONSTRAINT "PK_SourceDecks" PRIMARY KEY ("Id")
) TABLESPACE pg_default;

ALTER TABLE public."SourceDecks"
    OWNER to keyteki;

CREATE INDEX "IX_SourceDecks_Uuid"
    ON public."SourceDecks" USING btree
        ("Uuid" ASC NULLS LAST)
    TABLESPACE pg_default;